# Generated by Django 4.2 on 2023-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empno", models.IntegerField()),
                ("empname", models.CharField(max_length=233)),
                ("empsal", models.IntegerField()),
                ("empaddress", models.CharField(max_length=244)),
            ],
        ),
    ]
